### ISSUE TITLE
Move openxr off the main thread

### ISSUE THREAD

**Issue by jdm** [servo/webxr#113]
The following patches for webxr and servo do not work, because we panic in OpenXrDevice::new when calling `SurfmanDevice::from_current_context()`:
```diff
diff --git a/webxr/openxr/mod.rs b/webxr/openxr/mod.rs
index 518232f..5967e1f 100644
--- a/webxr/openxr/mod.rs
+++ b/webxr/openxr/mod.rs
@@ -19,6 +19,7 @@ use openxr::{
     Session, Space, Swapchain, SwapchainCreateFlags, SwapchainCreateInfo, SwapchainUsageFlags,
     Vector3f, ViewConfigurationType,
 };
+use std::sync::Arc;
 use std::rc::Rc;
 use surfman::platform::generic::universal::context::Context as SurfmanContext;
 use surfman::platform::generic::universal::device::Device as SurfmanDevice;
@@ -52,13 +53,15 @@ use input::OpenXRInput;
 
 const HEIGHT: f32 = 1.0;
 
+pub type GlFactory = Arc<dyn Fn() -> Rc<dyn Gl> + Send + Sync>;
+
 pub struct OpenXrDiscovery {
-    gl: Rc<dyn Gl>,
+    gl_factory: GlFactory,
 }
 
 impl OpenXrDiscovery {
-    pub fn new(gl: Rc<dyn Gl>) -> Self {
-        Self { gl }
+    pub fn new(gl_factory: GlFactory) -> Self {
+        Self { gl_factory }
     }
 }
 
@@ -108,8 +111,12 @@ impl DiscoveryAPI<SwapChains> for OpenXrDiscovery {
     ) -> Result<WebXrSession, Error> {
         let instance = create_instance().map_err(|e| Error::BackendSpecific(e))?;
         if self.supports_session(mode) {
-            let gl = self.gl.clone();
-            xr.run_on_main_thread(move || OpenXrDevice::new(gl, instance))
+            //let gl = self.gl.clone();
+            let factory = self.gl_factory.clone();
+            xr.spawn(move || {
+                let gl = factory();
+                OpenXrDevice::new(gl, instance)
+            })
         } else {
             Err(Error::NoMatchingDevice)
         }
```

```diff
diff --git a/ports/libsimpleservo/api/src/gl_glue.rs b/ports/libsimpleservo/api/src/gl_glue.rs
index b52fcadad3..f05eff2da3 100644
--- a/ports/libsimpleservo/api/src/gl_glue.rs
+++ b/ports/libsimpleservo/api/src/gl_glue.rs
@@ -32,6 +32,17 @@ pub mod egl {
         pub gl_context: EGLContext,
         pub display: EGLNativeDisplayType,
     }
+    
+    pub fn init_gl_fns() -> crate::gl_glue::ServoGl {
+        unsafe {
+            GlesFns::load_with(|addr| {
+                let addr = CString::new(addr.as_bytes()).unwrap();
+                let addr = addr.as_ptr();
+                let egl = Egl;
+                egl.GetProcAddress(addr) as *const c_void
+            })
+        }
+    }
 
     pub fn init() -> Result<EGLInitResult, &'static str> {
         info!("Loading EGL...");
@@ -39,12 +50,7 @@ pub mod egl {
             let egl = Egl;
             let display = egl.GetCurrentDisplay();
             egl.SwapInterval(display, 1);
-            let egl = GlesFns::load_with(|addr| {
-                let addr = CString::new(addr.as_bytes()).unwrap();
-                let addr = addr.as_ptr();
-                let egl = Egl;
-                egl.GetProcAddress(addr) as *const c_void
-            });
+            let egl = init_gl_fns();
             info!("EGL loaded");
             Ok(EGLInitResult {
                 gl_wrapper: egl,
diff --git a/ports/libsimpleservo/api/src/lib.rs b/ports/libsimpleservo/api/src/lib.rs
index 0b127eddb9..c2e990a477 100644
--- a/ports/libsimpleservo/api/src/lib.rs
+++ b/ports/libsimpleservo/api/src/lib.rs
@@ -34,6 +34,7 @@ use std::mem;
 use std::os::raw::c_void;
 use std::path::PathBuf;
 use std::rc::Rc;
+use std::sync::Arc;
 
 thread_local! {
     pub static SERVO: RefCell<Option<ServoGlue>> = RefCell::new(None);
@@ -165,11 +166,13 @@ pub fn is_uri_valid(url: &str) -> bool {
     ServoUrl::parse(url).is_ok()
 }
 
+pub type GlFactory = Arc<dyn Fn() -> Rc<dyn gl::Gl> + Send + Sync>;
+
 /// Initialize Servo. At that point, we need a valid GL context.
 /// In the future, this will be done in multiple steps.
 pub fn init(
     mut init_opts: InitOptions,
-    gl: Rc<dyn gl::Gl>,
+    gl_factory: GlFactory,
     waker: Box<dyn EventLoopWaker>,
     callbacks: Box<dyn HostTrait>,
 ) -> Result<(), &'static str> {
@@ -198,13 +201,14 @@ pub fn init(
         .or(blank_url)
         .unwrap();
 
+    let gl = gl_factory();
     gl.clear_color(1.0, 1.0, 1.0, 1.0);
     gl.clear(gl::COLOR_BUFFER_BIT);
     gl.finish();
 
     let window_callbacks = Rc::new(ServoWindowCallbacks {
         host_callbacks: callbacks,
-        gl: gl.clone(),
+        gl,
         coordinates: RefCell::new(init_opts.coordinates),
         density: init_opts.density,
         gl_context_pointer: init_opts.gl_context_pointer,
@@ -215,7 +219,7 @@ pub fn init(
         vr_init: init_opts.vr_init,
         xr_discovery: init_opts.xr_discovery,
         waker,
-        gl: gl.clone(),
+        gl_factory,
     });
 
     let servo = Servo::new(embedder_callbacks, window_callbacks.clone());
@@ -632,7 +636,7 @@ struct ServoEmbedderCallbacks {
     xr_discovery: Option<webxr::Discovery>,
     vr_init: VRInitOptions,
     #[allow(unused)]
-    gl: Rc<dyn gl::Gl>,
+    gl_factory: GlFactory,
 }
 
 struct ServoWindowCallbacks {
@@ -670,8 +674,8 @@ impl EmbedderMethods for ServoEmbedderCallbacks {
             self.xr_discovery.is_none(),
             "UWP builds should not be initialized with a WebXR Discovery object"
         );
-        let gl = self.gl.clone();
-        let discovery = webxr::openxr::OpenXrDiscovery::new(gl);
+        let gl_factory = self.gl_factory.clone();
+        let discovery = webxr::openxr::OpenXrDiscovery::new(gl_factory);
         registry.register(discovery);
     }
 diff --git a/ports/libsimpleservo/capi/src/lib.rs b/ports/libsimpleservo/capi/src/lib.rs
index 89d3b0f5c1..8410ac40af 100644
--- a/ports/libsimpleservo/capi/src/lib.rs
+++ b/ports/libsimpleservo/capi/src/lib.rs
@@ -15,7 +15,7 @@ use backtrace::Backtrace;
 #[cfg(not(target_os = "windows"))]
 use env_logger;
 use log::LevelFilter;
-use simpleservo::{self, gl_glue, ServoGlue, SERVO};
+use simpleservo::{self, gl_glue, GlFactory, ServoGlue, SERVO};
 use simpleservo::{
     Coordinates, EventLoopWaker, HostTrait, InitOptions, MediaSessionActionType,
     MediaSessionPlaybackState, MouseButton, VRInitOptions,
@@ -27,7 +27,7 @@ use std::os::raw::{c_char, c_void};
 use std::panic::{self, UnwindSafe};
 use std::slice;
 use std::str::FromStr;
-use std::sync::RwLock;
+use std::sync::{Arc, RwLock};
 
 extern "C" fn default_panic_handler(msg: *const c_char) {
     let c_str: &CStr = unsafe { CStr::from_ptr(msg) };
@@ -337,7 +337,7 @@ fn init_logger(_modules: &[*const c_char], _level: LevelFilter) {
 
 unsafe fn init(
     opts: CInitOptions,
-    gl: gl_glue::ServoGl,
+    gl_factory: GlFactory,
     gl_context: Option<*const c_void>,
     display: Option<*const c_void>,
     wakeup: extern "C" fn(),
@@ -401,7 +401,7 @@ unsafe fn init(
     let wakeup = Box::new(WakeupCallback::new(wakeup));
     let callbacks = Box::new(HostCallbacks::new(callbacks));
 
-    simpleservo::init(opts, gl, wakeup, callbacks).unwrap();
+    simpleservo::init(opts, gl_factory, wakeup, callbacks).unwrap();
 }
 
 #[cfg(target_os = "windows")]
@@ -412,11 +412,12 @@ pub extern "C" fn init_with_egl(
     callbacks: CHostCallbacks,
 ) {
     catch_any_panic(|| {
+        let gl_factory = Arc::new(|| gl_glue::egl::init_gl_fns());
         let gl = gl_glue::egl::init().unwrap();
         unsafe {
             init(
                 opts,
-                gl.gl_wrapper,
+                gl_factory,
                 Some(gl.gl_context),
                 Some(gl.display),
                 wakeup,
@@ -434,8 +435,8 @@ pub extern "C" fn init_with_gl(
     callbacks: CHostCallbacks,
 ) {
     catch_any_panic(|| {
-        let gl = gl_glue::gl::init().unwrap();
-        unsafe { init(opts, gl, None, None, wakeup, callbacks) }
+        let gl_factory = Arc::new(|| gl_glue::gl::init().unwrap());
+        unsafe { init(opts, gl_factory, None, None, wakeup, callbacks) }
     });
 }
```

**Comment by jdm** [comment]
It's possible that we might be able to work around this by obtaining surfman information on the main thread and then spawning the device, but I'm not sure if the d3d device that we extract from it is threadsafe or not.

**Comment by Manishearth** [comment]
Cc @asajeffrey

**Comment by jdm** [comment]
Alternatively may be we need to create a new surfman context in the new thread instead. I have forgotten some of the subtleties around our non-readback solution.

**Comment by asajeffrey** [comment]
Should we wait and see if this is still an issue with surfman 0.2? The API for bootstrapping servo has changed.

**Comment by jdm** [comment]
Can't hurt.

**Comment by jdm** [comment]
I have patches that create a new d3d11 device in the XR thread based on openxr's requirements and create a surfman device and context based on that (as well as the context descriptor obtained from the main thread that runs webrender). With this I am able to enter immersive mode without any panics, but nothing is rendered. Feels like progress, though!

**Comment by jdm** [comment]
I have a patch that causes a solid white texture to be rendered when running off the main thread in openxr. This means I can now focus on getting the real webgl texture to render, knowing that any rendering at all is possible. Definitely progress!

**Comment by jdm** [comment]
I have a branch that successfully renders webgl content off the main thread. Unfortunately when I create a new surfman device and use it (whether on or off the main thread), I get runaway memory usage and the device ooms.

**Comment by asajeffrey** [comment]
Hmm,  that's not good. I was getting a memory leak in the gstreamer plugin, but it mysteriously went away, perhaps due to bugfixes in surfman?

**Comment by jdm** [comment]
I have fixed the memory leak - it was a missing call to eglReleaseTexImage when destroying surface textures in surfman. This means I now have openxr successfully rendering webgl content off the main thread! \o/ I'll take more performance measurements on Monday.

**Comment by jdm** [comment]
https://github.com/servo/webxr/compare/master...jdm:solid
https://github.com/pcwalton/surfman/compare/master...jdm:angle-perf

**Comment by jdm** [comment]
Surprisingly enough, now that openxr is off the main thread, the main thread is dominating CPU time and the majority of that is spent in the rust allocator. This turns out to be caused by https://github.com/servo/ipc-channel/issues/254, because we're calling try_recv on in [this code](https://github.com/servo/webxr/blob/bf4e5a541bb2fcbace61cb1a071959bab10d9c19/webxr-api/registry.rs#L151-L153) every frame, so this allocates a bunch of boxes that are immediately thrown away.

**Comment by jdm** [comment]
After fixing ipc-channel to not box errors in the common case for try_recv, the main thread still consumes way more CPU than other threads because it thinks it's animating and runs as fast as possible. When I hack that out, it goes back to consuming much less CPU than the top three threads, which are 1) openxr, 2) webgl, 3) script.

**Comment by asajeffrey** [comment]
Hmm, why does it think it's animating, I wonder? It shouldn't (unless the web page is, in which case it's doing the right thing).

**Comment by jdm** [comment]
I set a breakpoint on some timer related code and discovered that Window::RequestAnimationFrame is being called every frame for reasons that are unclear. That would explain why the embedder believes that it's running animations.

**Comment by Manishearth** [comment]
@jdm hmm, I wonder what FPS we get for the very basic XR stuff done in https://manishearth.github.io/webgl-to-webxr/webxr-ar.html ?

**Comment by paulrouget** [comment]
> I set a breakpoint on some timer related code and discovered that Window::RequestAnimationFrame is being called every frame by three.js for reasons that are unclear. That would explain why the embedder believes that it's running animations.

The window animations are indeed running but not operational.

Adding a `animation.stop()` before returning [here](https://github.com/mrdoob/three.js/blob/r105/src/renderers/WebGLRenderer.js#L1067) will stop the calls.

I don’t see any code in threejs that would stop the animation loop. And there’s probably very little benefits for them to do so.

**Comment by asajeffrey** [comment]
> And there’s probably very little benefits for them to do so.

Well, on pretty much any browser implementation I can think of, running the window rAF is going to keep the compositor thread active, so there'll be more context switching on the CPU and extra activity on the GPU. I'd expect a perf hit on all browsers.

**Comment by paulrouget** [comment]
Isn't the screen with the window not visible (then rAF is not called) or visible, then the animation needs to keep running?

**Comment by paulrouget** [comment]
I'll file an issue to fix threejs, to either keep running the animation in the window, or just stop both animation and rAF loop.

**Comment by paulrouget** [comment]
@asajeffrey see Example 3: https://www.w3.org/TR/webxr/#animation-frames

**Comment by asajeffrey** [comment]
Oh that's interesting, I didn't know the webxr spec made changes to the window rAF. One thing that's funny is that that is non-normative text, is there anything normative that says this?

**Comment by Manishearth** [comment]
> I didn't know the webxr spec made changes to the window rAF

It doesn't; but the window isn't visible, so UAs may choose to not run rAF.

**Comment by asajeffrey** [comment]
Hmm, step 10.3 of https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering doesn't apply here, since the document has rAF callbacks.

**Comment by jdm** [comment]
This happened.
