### ISSUE TITLE
Unpaired wait() call in openxr initialization deprecated

### ISSUE THREAD

**Issue by jdm** [servo/webxr#146]
The upcoming changes to the OpenXR standard make xrWaitFrame calls that aren't paired with begin/end frame calls invalid. We will need to change https://github.com/servo/webxr/blob/master/webxr/openxr/mod.rs#L504-L505 to deal with this; apparently Servo doesn't work in the upcoming preview release on HoloLens devices because of this.

**Comment by jdm** [comment]
```
The rule is that xrWaitFrame will block until the previous frame has been 'begun' with xrBeginFrame, so if an xrBeginFrame call is omitted (e.g. two calls to xrWaitFrame) then the app will block indefinitely.
```

**Comment by Manishearth** [comment]
I think the easiest thing to do would be to send a dummy Views object initially, and if `self.frame_state` is unset (i.e. on the first frame) then we additionally send an `UpdateViews` event

**Comment by jdm** [comment]
We should fix this asap so our partners can test the new openxr implementation against servo.

**Comment by Manishearth** [comment]
Ah, on it.
