### ISSUE TITLE
surfman revision isn't pinned and breaks CI

### ISSUE THREAD

**Issue by jdm** [servo/webxr#178]
This currently makes it impossible to merge anything because surfman upstream made a breaking API change.

**Comment by asajeffrey** [comment]
This'll get fixed when we land https://github.com/servo/webxr/pull/176 and can go back to getting surfman from crates.io.

I did create a stop-gap https://github.com/asajeffrey/webxr/tree/patch-surfman if we want something to land faster, though it does use `[patch]` directives so it would be nice not to.

**Comment by asajeffrey** [comment]
Closed by #176
