### ISSUE TITLE
Hard dependency on x11

### ISSUE THREAD

**Issue by xhebox** [servo/webxr#193]
https://github.com/servo/webxr/blob/master/webxr/Cargo.toml#L44

It is causing a compilation error on pure-wayland env.

**Comment by Manishearth** [comment]
Happy to change it to an optional defaulted feature if you make a PR for it.

**Comment by xhebox** [comment]
I am not that familiar with rust, like so?
```
default = ["x11"]
x11 = []

[target.'cfg(feature = "x11")'.dependencies]
surfman = { version = "0.3", features = ["sm-x11"] }

[target.'cfg(not(feature = "x11"))'.dependencies]
surfman = "0.3"
```

**Comment by Manishearth** [comment]
The latter
