### ISSUE TITLE
Image is distorted using Meta headsets via SteamVR

### ISSUE THREAD

**Issue by msub2** [servo/webxr#217]
In both SteamVR via Link and SteamVR via Virtual Desktop there is noticeable skewing in the projected image. It is very similar to what I once observed in Wolvic, which was addressed with [this PR](https://github.com/Igalia/wolvic/pull/134), but I'm unsure if the exact same thing is happening here, as that fix was not for the OpenXR backend. This does not occur when using the Oculus OpenXR backend. Tested on Quest 3.

**Comment by msub2** [comment]
Worth noting that SteamVR via VDXR (Virtual Desktop's OpenXR runtime) renders perfectly with Quest 3, likely since VDXR wraps OVR stuff

**Comment by Manishearth** [comment]
This is the issue tracker for the specification. We do not manage individual implementations.

**Comment by msub2** [comment]
This isn't the spec repo though, this is Servo's implementation.

**Comment by Manishearth** [comment]
Oops! Got confused there (this happens often on the spec repo unfortunately and I misread the header)

**Comment by msub2** [comment]
Did a bit more exploration: I've noticed that as the session begins the projection will flip-flop between correct and incorrect a couple times before finally settling on the warped version. I'm not sure if this is a quirk with SteamVR or something that's not being caught in the OpenXR code yet
