### ISSUE TITLE
Render GL content in openxr backend

### ISSUE THREAD

**Issue by jdm** [servo/webxr#38]
> is this where we extract the D3D share handle and use that to draw the sub-parts of the texture to the D3D images?

Yes, because it's ANGLE backed we should be able to obtain the D3D texture id (or whatever it's called) and use that with D3D APIs.

_Originally posted by @Manishearth in https://github.com/servo/webxr/pull/37#issuecomment-519752150_

**Comment by jdm** [comment]
Based on https://github.com/Microsoft/angle/wiki/Interop-with-other-DirectX-code, perhaps we can:
* create a d3d texture from the [d3d11 device](https://github.com/servo/webxr/blob/95b32ca717b736025a43c2a55127a850caf7263f/webxr/openxr/mod.rs#L132)
* create an EGL surface during OpenXrDevice::new based on the shared shandle from the d3d texture
* create a GL texture and bind it to the new EGL surface
* create read and write framebuffers
* when it's time to render, bind the read and write buffers, attach the webgl texture to the read framebuffer and the shared d3d gl texture to the write framebuffer and use glBlitFramebuffers
* flush the GL pipeline
* draw the d3d texture to the swapchain images

**Comment by jdm** [comment]
cc @paulrouget

**Comment by Manishearth** [comment]
> draw the d3d texture to the swapchain images

I don't understand d3d terminology that well -- is this a blit? or just some kind of assignment? it would be nice to avoid double blitting

**Comment by jdm** [comment]
I know approximately nothing. Possibly @pcwalton has more experience.

**Comment by Manishearth** [comment]
So I think the swapchain images _are_ d3d textures (surfaces?), we don't need to create new ones, we just blit directly to them.

**Comment by Manishearth** [comment]
@paulrouget seemed to understand the DX stuff enough when we talked about this earlier.

**Comment by jdm** [comment]
One important feature of creating a new d3d11 texture is that we can add the D3D11_RESOURCE_MISC_SHARED flag when doing so. We might not be able to get a share handle from the swapchain textures that openxr creates.

**Comment by paulrouget** [comment]
I don't know enough to help at this point. Ashraf might be able to help.

**Comment by pcwalton** [comment]
We could possibly query the OpenXR textures to find out if they have that flag already, and only fall back to the extra blit if they don't.

Note that I'm rewriting a lot of the WebGL and rust-offscreen-rendering-context code right now to make this stuff significantly easier, by introducing a proper NativeSurface abstraction.

**Comment by jdm** [comment]
I've created a branch at https://github.com/servo/webxr/tree/d3d11-draw which creates a new sharable d3d texture, initializes it with solid red pixels, and then attempts to copy that texture data every frame into the swapchain textures from openxr. It builds but is completely untested.

**Comment by Manishearth** [comment]
Two bugs: we weren't using a format the swapchain liked (you can only copy between compatible formats), and we weren't setting the bounds correctly. We should ideally have all textures in the format we use with the swapchain; including GL textures when we instantiate the GL context. There's a `makeXRCompatible()` function on the webglrenderingcontext that should be able to do this.

With that I am able to get a red screen for a couple seconds until `CopySubresourceRegion` errors due to a corrupted first parameter. I'm not quite sure what's going on there, I printed all the poitner values and they seem fine.

**Comment by jdm** [comment]
It occurs to me - if we wanted to make progress in the short term with getting the GL texture data into D3D, we _could_ do a readback operation to get the pixel data out of GL, then create a new texture based on that pixel data and copy that into the swapchain texures (https://eatplayhate.me/2013/09/29/d3d11-texture-update-costs/). This is one of cases where "first make it work, then make it fast" may be the right choice for verifying that the architecture is _generally_ correct.

**Comment by Manishearth** [comment]
We still have the problem that dx is randomly deciding that our textures are corrupted, though.

**Comment by Manishearth** [comment]
Figured it out, winapi adopts ponters instead of retaining them, so we were double-freeing.

**Comment by Manishearth** [comment]
According to Jeff Gilbert:

> I believe you want https://searchfox.org/mozilla-central/source/gfx/angle/checkout/src/libGLESv2/entry_points_egl.cpp#739
> Or what we do in https://searchfox.org/mozilla-central/source/gfx/gl/SharedSurfaceANGLE.cpp, if you don't care about providing the exact D3DTexture
> ...
> Yes, so instead of drawing to a GL texture, you'll need to draw to an EGLSurface that's backed by an accessible D3DTexture.
> That's what SharedSurfaceANGLE is
> Use MakeCurrent to attach and detach the EGLSurface from the default-framebuffer (framebuffer 0) slot, and DXGIKeyedMutex to guarantee rendering results are synchronized properly

**Comment by Manishearth** [comment]
Current progress:

<details>

```patch
diff --git a/webxr/openxr/mod.rs b/webxr/openxr/mod.rs
index 1e42603..a3b62b0 100644
--- a/webxr/openxr/mod.rs
+++ b/webxr/openxr/mod.rs
@@ -119,6 +119,7 @@ struct OpenXrDevice {
     texture: ComPtr<d3d11::ID3D11Texture2D>,
     resource: ComPtr<dxgi::IDXGIResource>,
     device_context: ComPtr<d3d11::ID3D11DeviceContext>,
+    device: ComPtr<d3d11::ID3D11Device>,
 }
 
 impl OpenXrDevice {
@@ -258,7 +259,8 @@ impl OpenXrDevice {
             .create_swapchain(&swapchain_create_info)
             .map_err(|e| Error::BackendSpecific(format!("{:?}", e)))?;
 
-        let (texture, resource) = create_texture(&left_view_configuration, &right_view_configuration, device, format);
+        let (texture, resource) = create_texture(&left_view_configuration, &right_view_configuration, &device, format);
+
 
         Ok(OpenXrDevice {
             events: Default::default(),
@@ -281,6 +283,7 @@ impl OpenXrDevice {
             texture,
             resource,
             device_context,
+            device
         })
     }
 }
@@ -329,10 +332,50 @@ impl Device for OpenXrDevice {
 
     fn render_animation_frame(
         &mut self,
-        _texture_id: u32,
-        _size: UntypedSize2D<i32>,
+        texture_id: u32,
+        size: UntypedSize2D<i32>,
         sync: Option<GLsync>,
     ) {
+        let fb = self.read_fbo;
+        self.gl.bind_framebuffer(gl::FRAMEBUFFER, fb);
+        self.gl.bind_texture(gl::TEXTURE_2D, texture_id);
+
+        self.gl.framebuffer_texture_2d(gl::FRAMEBUFFER, gl::COLOR_ATTACHMENT0, gl::TEXTURE_2D, texture_id, 0);
+        let left_data = self.gl.read_pixels(0, 0, size.width  / 2, size.height, gl::RGBA, gl::UNSIGNED_BYTE);
+        println!("l {:?} {:?} {:?}", self.gl.get_error(), &left_data[0..5], &left_data[100..105]);
+        let right_data = self.gl.read_pixels(size.width / 2, 0, size.width / 2, size.height, gl::RGBA, gl::UNSIGNED_BYTE);
+        println!("r {:?} {:?} {:?}", self.gl.get_error(), &right_data[0..5], &right_data[100..105]);
+        self.gl.bind_framebuffer(gl::FRAMEBUFFER, 0);
+        let texture_desc = d3d11::D3D11_TEXTURE2D_DESC {
+            Width: (size.width / 2) as u32,
+            Height: size.height as u32,
+            Format: dxgiformat::DXGI_FORMAT_R8G8B8A8_UNORM,
+            MipLevels: 1,
+            ArraySize: 1,
+            SampleDesc: dxgitype::DXGI_SAMPLE_DESC {
+                Count: 1,
+                Quality: 0,
+            },
+            Usage: d3d11::D3D11_USAGE_DEFAULT,
+            BindFlags: d3d11::D3D11_BIND_RENDER_TARGET | d3d11::D3D11_BIND_SHADER_RESOURCE,
+            CPUAccessFlags: 0,
+            MiscFlags: d3d11::D3D11_RESOURCE_MISC_SHARED,
+        };
+        let mut init = d3d11::D3D11_SUBRESOURCE_DATA {
+            pSysMem: left_data.as_ptr() as *const _,
+            SysMemPitch: ((size.width / 2) * mem::size_of::<u32>() as i32) as u32,
+            SysMemSlicePitch: ((size.width / 2) * size.height * mem::size_of::<u32>() as i32) as u32,
+        };
+        let mut d3dtex_ptr = ptr::null_mut();
+        let (left, right) = unsafe {
+            self.device.CreateTexture2D(&texture_desc, &init, &mut d3dtex_ptr);
+            let left = ComPtr::from_raw(d3dtex_ptr);    
+            init.pSysMem = right_data.as_ptr() as *const _;     
+            self.device.CreateTexture2D(&texture_desc, &init, &mut d3dtex_ptr);
+            let right = ComPtr::from_raw(d3dtex_ptr);
+            (left.up::<d3d11::ID3D11Resource>(), right.up::<d3d11::ID3D11Resource>())
+        };
+
         // XXXManishearth this code should perhaps be in wait_for_animation_frame,
         // but we then get errors that wait_image was called without a release_image()
         self.frame_stream
@@ -354,20 +397,12 @@ impl Device for OpenXrDevice {
         let right_image = right_swapchain_images[self.right_image as usize];
 
         let texture_resource = self.texture.clone().up::<d3d11::ID3D11Resource>();
-        let left_box = d3d11::D3D11_BOX {
+        let b = d3d11::D3D11_BOX {
             left: 0,
             top: 0,
             front: 0,
-            right: self.left_extent.width as u32,
-            bottom: self.left_extent.height as u32,
-            back: 1,
-        };
-        let right_box = d3d11::D3D11_BOX {
-            left: self.left_extent.width as u32,
-            top: 0,
-            front: 0,
-            right: self.left_extent.width as u32 + self.right_extent.width as u32,
-            bottom: self.right_extent.height as u32,
+            right: (size.width / 2) as u32,
+            bottom: size.height as u32,
             back: 1,
         };
         unsafe {
@@ -378,8 +413,8 @@ impl Device for OpenXrDevice {
             mem::forget(left_resource.clone());
             let right_resource = ComPtr::from_raw(right_image).up::<d3d11::ID3D11Resource>();
             mem::forget(right_resource.clone());
-            self.device_context.CopySubresourceRegion(left_resource.as_raw(), 0, 0, 0, 0, texture_resource.as_raw(), 0, &left_box);
-            self.device_context.CopySubresourceRegion(right_resource.as_raw(), 0, 0, 0, 0, texture_resource.as_raw(), 0, &right_box);
+            self.device_context.CopySubresourceRegion(left_resource.as_raw(), 0, 0, 0, 0, left.as_raw(), 0, &b);
+            self.device_context.CopySubresourceRegion(right_resource.as_raw(), 0, 0, 0, 0, right.as_raw(), 0, &b);
         }
 
         self.left_swapchain.release_image().unwrap();
@@ -523,7 +558,7 @@ fn init_device_for_adapter(
 fn create_texture(
     left_view_configuration: &ViewConfigurationView,
     right_view_configuration: &ViewConfigurationView,
-    device: ComPtr<ID3D11Device>,
+    device: &ComPtr<ID3D11Device>,
     format: dxgiformat::DXGI_FORMAT,
 ) -> (ComPtr<d3d11::ID3D11Texture2D>, ComPtr<dxgi::IDXGIResource>) {
     let width = left_view_configuration.recommended_image_rect_width + right_view_configuration.recommended_image_rect_width;
```

</details>

It doesn't seem to be working, sadly. I did get it to somehow copy the rendered servo window into the texture, though, I think you can get that behavior by removing the second `bind_framebuffer`.

**Comment by Manishearth** [comment]
@paulrouget would you be able to try out the approach in https://github.com/servo/webxr/issues/38#issuecomment-520192224 ? I think I'm blundering through lots of beginner OpenGL mistakes since I've not used it in ages.

**Comment by paulrouget** [comment]
I'm in the same boat. I'm not comfortable enough with OpenGL in general. I could look, but maybe someone else would do better job than me. @jdm, any idea who could help here?

**Comment by jdm** [comment]
Manish sg and I are continuing to investigate. I have a debug ANGLE build, which takes a lot of a the guesswork out of the process.

**Comment by jdm** [comment]
With https://www.joshmatthews.net/webgl-to-webxr/webxr-ar.html, I get grey pixels in the immersive view in the emulator with Manish's earlier patch applied. The only difference is that I added a gl.finish() to the end of the renderVR JS function.

**Comment by gterzian** [comment]
Are you sure you need a left/right swapchains and textures? I'm just looking into the Chromium code and what caught my attention is that they seem to use only one:

There is a comment:

> // WebVR and WebXR textures are double wide, meaning the texture contains
  // both the left and the right eye, so the width of the swapchain texture
  // needs to be doubled.

https://github.com/chromium/chromium/blob/f6e78d1e83f4717cbae727fbade457c7d5791b49/device/vr/openxr/openxr_api_wrapper.cc#L335

Maybe it's a different version or something...

**Comment by Manishearth** [comment]
We _can_ use one swapchain/texture.

However, I was informed that the OpenXR Hololens implementation when given a double-wide texture will do a blit _anyway_. Given that we're already forced to do a blit (currently a readback copy, even) it's best to use that blit to also convert things into a format openxr will like.

**Comment by jdm** [comment]
Since we render content successfully, I'm going to go ahead and close this.
