### ISSUE TITLE
Can't compile magicleap on macOS

### ISSUE THREAD

**Issue by jkelleyrtp** [servo/webxr#52]
```
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```
macOS doesn't have llvm-config and thus can't link to the magcleap libraries. How would I go about fixing this?

**Comment by asajeffrey** [comment]
You need to compile using the magicleap SDK.

**Comment by jkelleyrtp** [comment]
Do I set this using a rustc flag to the mlsdk? Not sure which compiler I should use and where it's located.

**Comment by asajeffrey** [comment]
The SDK is available from https://creator.magicleap.com, once you've installed it, you should set the MAGICLEAP_SDK environment variable to point to the download, and run `cargo build --features=magicleap`.

**Comment by msub2** [comment]
@jdm This can be closed now that the ML backend has been removed.
