### ISSUE TITLE
assertion failure. Wrong FXGI format

### ISSUE THREAD

**Issue by paulrouget** [servo/webxr#54]
Running into this: https://github.com/servo/webxr/blob/892530cbd6969316f42b1daafd279e933b73470c/webxr/openxr/mod.rs#L661

Running this: https://www.joshmatthews.net/webgl-to-webxr/webxr-ar.html

**Comment by Manishearth** [comment]
What's the actual format? as long as it's R8G8B8A8 it should be fine, and we can make the assertion more general.

If it's a different format we can change the code to handle multiple formats.

**Comment by paulrouget** [comment]
`B8G8R8A8_UNORM`

**Comment by Manishearth** [comment]
Hmm.

Is the other one in `enumerate_swapchain_formats`? If so we can replace the assert with a find on https://github.com/servo/webxr/blob/892530cbd6969316f42b1daafd279e933b73470c/webxr/openxr/mod.rs#L204

**Comment by jdm** [comment]
https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/master/README.md#select-a-pixel-format

**Comment by Manishearth** [comment]
I'm hitting this as well now. Perhaps they changed the defaults? We should move over to the recommended one, but also support actual format selection.
