### ISSUE TITLE
Use surfman for surface sharing

### ISSUE THREAD

**Issue by asajeffrey** [servo/webxr#60]
Surfman is the next-generation of offscreen-gl-context, with support for surface sharing. We should use it rather than texture sharing and `GLSync` in webxr.

**Comment by asajeffrey** [comment]
The relevant branch is https://github.com/asajeffrey/webxr/tree/surfman.

**Comment by Manishearth** [comment]
Is there a corresponding servo branch to test this with?

**Comment by asajeffrey** [comment]
@Manishearth https://github.com/pcwalton/servo/tree/texture-sharing-iosurface

**Comment by asajeffrey** [comment]
I'm not sure if anything other than glwindow works in https://github.com/pcwalton/servo/tree/texture-sharing-iosurface. It's also more than 700 commits behind master!
