### ISSUE TITLE
Panic creating the d3d texture in openxr

### ISSUE THREAD

**Issue by jdm** [servo/webxr#68]
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `87`', C:\Users\image\.cargo\git\checkouts\webxr-702fa5244eec1e69\a7e8cae\webxr\openxr\mod.rs:701:5
```
This corresponds to:
```
    assert_eq!(format, dxgiformat::DXGI_FORMAT_B8G8R8A8_UNORM);
```
I'm using the latest HoloLens 2 emulator image (10.0.18362.1031) on master Servo.

**Comment by Manishearth** [comment]
Okay so we basically need to bite the bullet and support multiple formats, since it panics on my device if this is changed :smile:

**Comment by Manishearth** [comment]
Though, curiously: IIRC this value is set by the openxr backend, not the device.

**Comment by jdm** [comment]
I always have to install the latest openxr backend in the emulator, so maybe something changed in a new release.

**Comment by Manishearth** [comment]
Oh when I said backend I meant the nuget package, but it could also be that backend

https://github.com/microsoft/OpenXR-SDK-VisualStudio#select-a-pixel-format suggests we're doing the right thing here.

Actually, I bet your device _does_ support this pix format, it's just not the _first_ in the list of formats it supports. Which would be fixed if we actually implemented selection.

**Comment by jdm** [comment]
I'll see if I can get that working today.
