### ISSUE TITLE
Hololens rendering not stable

### ISSUE THREAD

**Issue by Manishearth** [servo/webxr#80]
The object we render seems to move around a little bit as the user moves around. This is somewhat clear if you shake your head a bit, but very clear if you walk back a couple yards (any floating object will move like a third of that distance towards you)

I'm not quite sure what's going on here. It feels like the projection is being squashed, but I copied over projection matrix values from BasicXRApp and it didn't help. Perhaps our pose data is being scaled somehow?

cc @jdm @paulrouget

**Comment by paulrouget** [comment]
I'm not sure I can reproduce this.

There's a bit of delay between the head movement and the position, but I also see that with other apps.

When I start a webxr demo, then step back ~3 meters, I don't see any weird positioning.

Can you give me some specific STR, then I'll try here see if I can reproduce.

**Comment by paulrouget** [comment]
If it were an issue with your device, I guess you would see the same bug with non-servo app.

**Comment by Manishearth** [comment]
@paulrouget I'm using the https://manishearth.github.io/webxr-three/examples/webvr_paint.html and https://manishearth.github.io/webxr-three/examples/webvr_lorenzattractor.html examples.

Compare it with [BasicXRApp](https://github.com/microsoft/OpenXR-SDK-VisualStudio/tree/master/samples/BasicXrApp), which lets you place cubes by "clicking". I can walk a couple meters away from the cube and it seems to stay put. If I do the same an object drawn in webvr_paint, it doesn't seem to do so.

With the lorenz attractor it also seems to not stay put, instead moving along with your head a little bit

**Comment by paulrouget** [comment]
I can reproduce with webvr_paint. No I have doublt about https://servo.org/hl-home/webxr-ar.html - I don't see obvious jittering, even though it's shaking a little bit.

Could it be an issue with threejs?

**Comment by Manishearth** [comment]
@paulrouget the issue isn't jittering

The problem is that it's not projecting well: if you have an object placed at a certain point, and move away from it, to some extent it moves with you.
