### ISSUE TITLE
openxr - Backend requested unsupported format 91

### ISSUE THREAD

**Issue by paulrouget** [servo/webxr#83]
Running https://github.com/servo/servo/commit/2aca5c82e475b41da24adc7899423bbcb0966b32 - getting these warnings on the device:

```
RUST: WARN - webxr::openxr - Available formats: [91, 87, 28, 29, 55, 45, 40, 20]
RUST: WARN - webxr::openxr - Backend requested unsupported format 91
```

**Comment by Manishearth** [comment]
Note: this isn't a bug, it means we skipped over 91 and picked 87, which is fine. We print out unsupported formats so that we can add support for them in the future.

91 is `DXGI_FORMAT_B8G8R8A8_UNORM_SRGB`, we could add support for that. Unsure if the srgb part needs special handling.

**Comment by paulrouget** [comment]
Thanks.

**Comment by Manishearth** [comment]
Oh, i was going to leave this open for the srgb thing. Filed a new issue https://github.com/servo/webxr/issues/84
