### ISSUE TITLE
Create longer-lived reference spaces in webxr backend

### ISSUE THREAD

**Issue by jdm** [servo/webxr#94]
> I'm also seeing action spaces and reference spaces being created and destroyed every frame. I don't think this will cause a problem, but they aren't intended to be used with such a short lifespan. Generally apps create spaces and keep them around for the lifetime of the session

From our MS friends.

**Comment by Manishearth** [comment]
Should be easy to fix

**Comment by Manishearth** [comment]
I don't see us creating any reference spaces, only action spaces.
